array = [10,20,30,40,50]
console.log(array[1])
try {
    console.log(arry[4])
}
catch(err){
    console.log("there is error")
}


a = 20
try {
    console.log(c)
}
catch(err){
    console.log(err.message)
}
finally{
    console.log("this is finally block")
}

console.log(array[2])